In [1]:
import numpy as np

In [10]:
a = np.array(
    [
        [-1, -2, -3],
        [10, 20, 30]
    ]
)

b = np.array(
    [
        [100],
        [100]
    ]
)

In [11]:
c = a + b

In [12]:
print(c)

[[ 99  98  97]
 [110 120 130]]


In [13]:
a = np.array(
    [
        [-1, -2, -3],
        [10, 20, 30]
    ]
)

b = np.array(
    [
        [100],
        [100]
    ]
)

In [14]:
d = a * b

In [15]:
print(d)

[[-100 -200 -300]
 [1000 2000 3000]]
